version: '3.2'

services:
  app:
      image: app
      build:
        context: .
        dockerfile: ./Dockerfile
      ports:
        - 5000:5000
      command: >
        bash -c "FLASK_APP=run.py && flask run --host=0.0.0.0"